#debug: true
#debug: false

logging:
  level:
    root: INFO
    net:
      mmeany: TRACE
    org:
      springframework:
        security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%method:%line] - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  info:
    env:
      enabled: true
    git:
      mode: full
    java:
      enabled: true

app-config:
  allowedOrigins: https://mmeany.net,https://www.mmeany.net
  users:
    - username: mark
      password: _undisclosed_
      encrypted: "${BASIC_AUTH_PASSWORD:{noop}Password123}"
      roles: ADMIN
  keycloak:
    jwt-mode: PUBLIC_KEY
    client-id: blog-service
    # http://KEYCLOAK_SERVER_BASE_URL/realms/REALM
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuKZc5S1ulwtjTZwTuan87op+d4ZNKLewjlMU+R9kljmbCEyYPeoPLc4UfdRr5tSR/5XiDMvWCZ9hPR+keSstC3OBRBkvZwowBCAhckFIb1OymX6pb53Z82mhTLZIPy5Ur+sqyjIzVYfD7xTOXFSJdJ6aSQAg0h0kL19VM/lbUBp8N87RpR+KRb6Bh9F1G/3Xciu+UdglnEu9kpqbvHqNoVPoy80PklQfI8DkLrbTPcF5qXOiF/v3AZCtmpTYdmCQOUx8Dr83iXmUDNv2hWeMh24DzkvOZ5nLWLlGu/dI4afZBJYKOgYhvypU/bO2NlYupokBhYR/nr9fo+yiJe4cwwIDAQAB
    conversion-strategy: BOTH

server:
  port: ${PORT:9081}
  servlet:
    session:
      timeout: 1h

spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      # Clients can wait for up to 2 seconds
      connection-timeout: 2000
      # Connections recycled after 30 minutes
      max-lifetime: 1800000
      maximum-pool-size: 10
      # Always keep at least one idle connection in the pool
      minimum-idle: 1
      # Expunge a connection after it has been idle for 30 seconds
      idle-timeout: 30000
      autoCommit: false
    username: mark
    password: my-secret-pw
    # See: https://vladmihalcea.com/mysql-jdbc-statement-caching/
    url: jdbc:postgresql://localhost:5432/mvm
  jpa:
    open-in-view: false
    properties:
      hibernate:
        cache:
          use_query_cache: false
          use_second_level_cache: false
          region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
        generate_statistics: false
        hbm2ddl:
          # drop-create create update validate none
          auto: update
    show-sql: true

---
spring.config.activate.on-profile: test

logging:
  level:
    root: INFO
    net:
      mmeany: TRACE


---
spring.config.activate.on-profile: test-containers

#spring.jpa.properties.hibernate.integration.envers.enabled: false

server:
  port: 0

app-config:
  allowedOrigins: http://mmeany.net,http://*.mmeany.net,http://*.mmeany.net:8080,http://localhost:8080
  users:
    - username: mark
      password: Password123
      encrypted: "{noop}Password123"
      roles: ADMIN
  keycloak:
    # With jwt-mode set to JWKS, TestContainers configuration will set spring.security.oauth2.resourceserver.jwt.jwk-set-uri
    jwt-mode: JWKS
    client-id: blog-service
    # from src/test/resources/dev-realm.json
    client-secret: bRXguGMmWUCFKWJcMJeJgnNbuQBZVT2u
    public-key:
    conversion-strategy: BOTH

logging:
  #  file:
  #    path: build
  #    name: mvm-cucumber.log
  level:
    root: INFO
    net:
      mmeany: TRACE
    org:
      springframework: INFO
      #security: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%method:%line] - %msg%n"
